### ISSUE TITLE
VanishNoPacket Issue after updating to 3.18.2

### ISSUE THREAD

**Issue by alexratman** [mbax/VanishNoPacket#471]
08.08 15:48:36 [Server] INFO at org.kitteh.vanish.hooks.HookManager.registerHook(HookManager.java:141)
08.08 15:48:36 [Server] INFO at java.lang.Class.getConstructor(Class.java:1676)
08.08 15:48:36 [Server] INFO at java.lang.Class.getConstructor0(Class.java:2723)
08.08 15:48:36 [Server] INFO at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413)
08.08 15:48:36 [Server] INFO at java.lang.Class.getDeclaredConstructors0(Native Method)
08.08 15:48:36 [Server] INFO java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
08.08 15:48:36 [Server] SEVERE Error occurred while enabling VanishNoPacket v3.18.2 (Is it up to date?)
08.08 15:48:36 [Server] INFO Now hooking into Essentials

I have not updated essentials and I only updated VanishNoPacket and CoreProtect. Would like to add that I am using spigot
